//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Covi.Features.AccountFeaturesInformation.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Covi.Features.AccountFeaturesInformation.Resources.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next step.
        /// </summary>
        internal static string AccountInfo_Btn_Text {
            get {
                return ResourceManager.GetString("AccountInfo_Btn_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About your HealthBuddy profile.
        /// </summary>
        internal static string AccountInfo_Title_Text {
            get {
                return ResourceManager.GetString("AccountInfo_Title_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In this version you will only receive health information.
        /// </summary>
        internal static string AnonymProfile_Instruction_Text1 {
            get {
                return ResourceManager.GetString("AnonymProfile_Instruction_Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can upgrade to the advanced version of this app at any time by creating an account.
        /// </summary>
        internal static string AnonymProfile_Instruction_Text2 {
            get {
                return ResourceManager.GetString("AnonymProfile_Instruction_Text2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The information you provide will remain private, confidential and secure.
        /// </summary>
        internal static string RegisteredProfile_Instruction_Text1 {
            get {
                return ResourceManager.GetString("RegisteredProfile_Instruction_Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only you can access your profile information.
        /// </summary>
        internal static string RegisteredProfile_Instruction_Text2 {
            get {
                return ResourceManager.GetString("RegisteredProfile_Instruction_Text2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please note down your username and password. If you forget it, you will need to re-register.
        /// </summary>
        internal static string RegisteredProfile_Instruction_Text3 {
            get {
                return ResourceManager.GetString("RegisteredProfile_Instruction_Text3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We are using Bluetooth to check if you have been in contact with someone infected so as we can notify you.
        /// </summary>
        internal static string RegisteredProfile_Instruction_Text4 {
            get {
                return ResourceManager.GetString("RegisteredProfile_Instruction_Text4", resourceCulture);
            }
        }
    }
}
