//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Covi.Features.OnBoarding.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Covi.Features.OnBoarding.Resources.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission to use bluetooth was denied. Please, grant permission to use bluetooth in the application settings to proceed..
        /// </summary>
        internal static string BluetoothNotification_Denied_ErrorText {
            get {
                return ResourceManager.GetString("BluetoothNotification_Denied_ErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bluetooth is currently unavailable. Either bluetooth is not supported by your device or it is disabled. Please, check device bluetooth settings..
        /// </summary>
        internal static string BluetoothNotification_Disabled_ErrorText {
            get {
                return ResourceManager.GetString("BluetoothNotification_Disabled_ErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bluetooth error..
        /// </summary>
        internal static string BluetoothNotification_Error_Title {
            get {
                return ResourceManager.GetString("BluetoothNotification_Error_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your device has some hardware limitations and might be invisible to other devices via Bluetooth..
        /// </summary>
        internal static string BluetoothNotification_NotSupported_WarningText {
            get {
                return ResourceManager.GetString("BluetoothNotification_NotSupported_WarningText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bluetooth warning..
        /// </summary>
        internal static string BluetoothNotification_Warning_Title {
            get {
                return ResourceManager.GetString("BluetoothNotification_Warning_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tailored for you.
        /// </summary>
        internal static string OnBoardind_MadeForYou_SubTitle {
            get {
                return ResourceManager.GetString("OnBoardind_MadeForYou_SubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For this app to work and help save lives, please connect with bluetooth.
        /// </summary>
        internal static string OnBoarding_Connectivity_ErrorText {
            get {
                return ResourceManager.GetString("OnBoarding_Connectivity_ErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100% anonymous
        ///We do not know your name or location.
        /// </summary>
        internal static string OnBoarding_Connectivity_Instruction1 {
            get {
                return ResourceManager.GetString("OnBoarding_Connectivity_Instruction1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This app uses bluetooth to trace if you&apos;ve been in contact with someone who is infected.
        /// </summary>
        internal static string OnBoarding_Connectivity_Instruction2 {
            get {
                return ResourceManager.GetString("OnBoarding_Connectivity_Instruction2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We will only use the bluetooth and not the location when you give permission.
        /// </summary>
        internal static string OnBoarding_Connectivity_Instruction4_AndroidOnly {
            get {
                return ResourceManager.GetString("OnBoarding_Connectivity_Instruction4_AndroidOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect with Bluetooth.
        /// </summary>
        internal static string OnBoarding_Connectivity_SubTitle {
            get {
                return ResourceManager.GetString("OnBoarding_Connectivity_SubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connectivity.
        /// </summary>
        internal static string OnBoarding_Connectivity_Title {
            get {
                return ResourceManager.GetString("OnBoarding_Connectivity_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recommendations tailored to your profile category.
        /// </summary>
        internal static string OnBoarding_MadeForYou_Instruction1 {
            get {
                return ResourceManager.GetString("OnBoarding_MadeForYou_Instruction1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area specific risks, recommendations and behaviour rules.
        /// </summary>
        internal static string OnBoarding_MadeForYou_Instruction2 {
            get {
                return ResourceManager.GetString("OnBoarding_MadeForYou_Instruction2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NO private information shared.
        /// </summary>
        internal static string OnBoarding_MadeForYou_Instruction3 {
            get {
                return ResourceManager.GetString("OnBoarding_MadeForYou_Instruction3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Made for you.
        /// </summary>
        internal static string OnBoarding_MadeForYou_Title {
            get {
                return ResourceManager.GetString("OnBoarding_MadeForYou_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next step.
        /// </summary>
        internal static string OnBoarding_Next_Button_Text {
            get {
                return ResourceManager.GetString("OnBoarding_Next_Button_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For this app to work and help save lives, please allow notifications.
        /// </summary>
        internal static string OnBoarding_Notifications_ErrorText {
            get {
                return ResourceManager.GetString("OnBoarding_Notifications_ErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In-app notifications tell you if you&apos;ve been in contact with someone who is infected.
        /// </summary>
        internal static string OnBoarding_Notifications_Instruction1 {
            get {
                return ResourceManager.GetString("OnBoarding_Notifications_Instruction1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We don&apos;t have your contact details, so we will never email or text you.
        /// </summary>
        internal static string OnBoarding_Notifications_Instruction2 {
            get {
                return ResourceManager.GetString("OnBoarding_Notifications_Instruction2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications will be sent through the app only.
        /// </summary>
        internal static string OnBoarding_Notifications_Instruction3 {
            get {
                return ResourceManager.GetString("OnBoarding_Notifications_Instruction3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Important notifications.
        /// </summary>
        internal static string OnBoarding_Notifications_Title {
            get {
                return ResourceManager.GetString("OnBoarding_Notifications_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All information transmitted via encryption.
        /// </summary>
        internal static string OnBoarding_Privacy_Instruction1 {
            get {
                return ResourceManager.GetString("OnBoarding_Privacy_Instruction1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NO information is linked to your identity.
        /// </summary>
        internal static string OnBoarding_Privacy_Instruction2 {
            get {
                return ResourceManager.GetString("OnBoarding_Privacy_Instruction2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NO personal information leaves your phone.
        /// </summary>
        internal static string OnBoarding_Privacy_Instruction3 {
            get {
                return ResourceManager.GetString("OnBoarding_Privacy_Instruction3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completely anonymous.
        /// </summary>
        internal static string OnBoarding_Privacy_SubTitle {
            get {
                return ResourceManager.GetString("OnBoarding_Privacy_SubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy.
        /// </summary>
        internal static string OnBoarding_Privacy_Title {
            get {
                return ResourceManager.GetString("OnBoarding_Privacy_Title", resourceCulture);
            }
        }
    }
}
