//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Covi.Features.Polls.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Covi.Features.Polls.Resources.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create account.
        /// </summary>
        internal static string Polls_CreateAccount_BtnText {
            get {
                return ResourceManager.GetString("Polls_CreateAccount_BtnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polls.
        /// </summary>
        internal static string Polls_HeaderTitle_Text {
            get {
                return ResourceManager.GetString("Polls_HeaderTitle_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As it stands you have chosen the information only option.
        /// </summary>
        internal static string Polls_InfoItem1_Text {
            get {
                return ResourceManager.GetString("Polls_InfoItem1_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To get access to polls and your full HealthBuddy advanced profile, please login or sign up for free if you do not have an account.
        /// </summary>
        internal static string Polls_InfoItem2_Text {
            get {
                return ResourceManager.GetString("Polls_InfoItem2_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type your answer here.
        /// </summary>
        internal static string Polls_Input_Placeholder_Text {
            get {
                return ResourceManager.GetString("Polls_Input_Placeholder_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Have an account? Sign in.
        /// </summary>
        internal static string Polls_LogIn_BtnText {
            get {
                return ResourceManager.GetString("Polls_LogIn_BtnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only registered users can paticipate in polls.
        /// </summary>
        internal static string Polls_Restricted_TitleText {
            get {
                return ResourceManager.GetString("Polls_Restricted_TitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POLLS.
        /// </summary>
        internal static string Polls_Title_Text {
            get {
                return ResourceManager.GetString("Polls_Title_Text", resourceCulture);
            }
        }
    }
}
